### ISSUE TITLE
What variables give the best results?

### ISSUE THREAD

**Issue by miranthajayatilake** [DAI-Lab/TGAN#1]
Hi,

Great work on this execution! 

Due to GPU limitations I'm currently having I was not able to run the entire `launcher.py` as in the repo. But I ran `TGAN_synthesizer.py` separately on several datasets and the results were somewhat ok.

Can I have an idea on what tunable parameters out of below gave the best results according to your experience? 
```
tunable_variables = {
    "--batch_size": [50, 100, 200],
    "--z_dim": [50, 100, 200, 400],
    "--num_gen_rnn": [100, 200, 300, 400, 500, 600],
    "--num_gen_feature": [100, 200, 300, 400, 500, 600],
    "--num_dis_layers": [1, 2, 3, 4, 5],
    "--num_dis_hidden": [100, 200, 300, 400, 500],
    "--learning_rate": [0.0002, 0.0005, 0.001],
    "--noise": [0.05, 0.1, 0.2, 0.3]
}
```

For example on the **Census dataset**.

Thank you!

**Comment by leix28** [comment]
Here are the hyper parameters we used.
```
--batch_size 200
--num_gen_rnn 400 
--num_gen_feature 200 
--num_dis_layers 2 
--num_dis_hidden 200 
--z_dim 200 
--learning_rate 0.0005
--noise 0.2
```
