### ISSUE TITLE
Understand stats in Trainlog file

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [DAI-Lab/TGAN#12]
`{"QueueInput/queue_size": 50.0, "GAN_loss/gen/loss": 0.9750093221664429, "GAN_loss/gen/klloss": 0.27809518575668335, "GAN_loss/gen/final-g-loss": 1.2531044483184814, "GAN_loss/discrim/loss": 0.6561644077301025, "GAN_loss/discrim/accuracy_real": 0.0, "GAN_loss/discrim/accuracy_fake": 1.0, "epoch_num": 5, "global_step": 1000}`
Could you please clarify these metric and their values. How good or how bad it is?

**Comment by ManuelAlvarezC** [comment]
Hi @TrinhDinhPhuc,

I see in these values that you are still training with 200 steps per epoch. As we discussed in #8, this is absolutely not enough, so these results are obviously awful. Please fix this before starting to think about any results.

Regarding what the values mean, these are the scores obtained during the evaluation. Please make sure to review the paper to have better understanding of those.

**Comment by TrinhDinhPhuc** [comment]
Oh sorry, i copied the stats of the old one. This is the stats file which was training with 10000 steps per epoch. Please open this issue. Thanks
`{"QueueInput/queue_size": 50.0, "GAN_loss/gen/loss": 1.6636285781860352, "GAN_loss/gen/klloss": 0.10859352350234985, "GAN_loss/gen/final-g-loss": 1.7722220420837402, "GAN_loss/discrim/loss": 0.6533578038215637, "GAN_loss/discrim/accuracy_real": 0.5799999833106995, "GAN_loss/discrim/accuracy_fake": 0.800000011920929, "epoch_num": 5, "global_step": 50000}]`
