### ISSUE TITLE
Understand parameters in exp-params.json file

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [DAI-Lab/TGAN#13]
I am reading parameters in `exp-params.json` file. There are some parameters I don't understand them completely. Could you please explain it to me?
```
"--noise", "0.3"
 "--z_dim", "50"
 "--num_gen_rnn","100"
"--num_gen_feature", "500"
 "--num_dis_layers", "5"
```

**Comment by ManuelAlvarezC** [comment]
Hi @TrinhDinhPhuc,

Sure:

* `z_dim`: Number of dimensions in the noise input for the generator.
* `noise`: Upper bound to the gaussian noise added to categorical columns.
* `num_gen_rnn`: Number of units in rnn cell in generator.
* `num_gen_feature`: Number of units in fully connected layer in generator.
* `num_dis_layers`: Number of layers in discriminator.
