### ISSUE TITLE
Vector Dimensions

### ISSUE THREAD

**Issue by yuanyingfang23** [DAI-Lab/TGAN#14]
Hi, could I ask how you deal with the different dimensions vectors in Generator part? Since categorical data converted into one-hot learning vector may has larger dimensions than continuous data as input.

**Comment by leix28** [comment]
The LSTM generates feature vectors for each column. Then a column specific fully connected layer is responsible for converting a feature vector to an output vector. Since each column has its own fully connected layer, a vector with correct size can be generated for each column.

**Comment by yuanyingfang23** [comment]
> The LSTM generates feature vectors for each column. Then a column specific fully connected layer is responsible for converting a feature vector to an output vector. Since each column has its own fully connected layer, a vector with correct size can be generated for each column.

Hi Lei, thanks for your reply. For my current understanding, the generator part is implemented by LSTM, tabular data in a row will be looked as a sequence, each column represents each time step. Afterwards,  each time step in LSTM will be processed by different fully connected layers separately? In this way, weights in each individual full connected layer does not share to others.

**Comment by leix28** [comment]
> In this way, weights in each individual full connected layer does not share to others.

Correct.

**Comment by yuanyingfang23** [comment]
Thanks a lot
