### ISSUE TITLE
Why restoring checkpoint is run on CPU not GPU?

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [DAI-Lab/TGAN#17]
This is my question, which has been posted on SOF https://stackoverflow.com/questions/55755668/why-restoring-checkpoint-is-run-on-cpu-not-gpu
Could you please explain it to me?

**Comment by ManuelAlvarezC** [comment]
Hi @TrinhDinhPhuc,

Could you post the commands you used and the full output in order to reproduce the issue?
Also, at what moments where you checking using nvidia-smi? 

Thanks.

**Comment by TrinhDinhPhuc** [comment]
I just followed your instruction in README file. I check **nvidia-smi** when it was training, each epoch only need a few minutes to finish. But in the restoring checkpoint period, i checked again the python process on GPU was gone, That why restoring checkpoint needed 4-5 hours to finish.

**Comment by ManuelAlvarezC** [comment]
From what you say, it clearly seems that the research version of TGAN was not restoring the checkpoints properly.
In any case, we have just released a new version of the software, which is the one that will be maintained from now on, so it would be better if you switch to the latest one.
Bear in mind that GPU support has been temporarily removed in this later version but will be added back shortly #21
