### ISSUE TITLE
List of all the requirements for TGAN installation?

### ISSUE THREAD

**Issue by soft-nougat** [DAI-Lab/TGAN#19]
Hey Team,

Thanks so much for this package! :)

Can you please confirm all of the requirements for TGAN installation? I remember there being a section in readme about this, but right now it only states Python is a requirement. Sorry if I am missing something!

Thanks again,
Tia

**Comment by csala** [comment]
Hi @soft-nougat 

Dependencies are now implicitly listed inside the `setup.py` file.

However, from now TGAN can be installed as a standard python package using [pip](https://pypi.org/project/pip/), so you do not need to care about dependencies anymore, as `pip` takes care of them when you issue the `pip install tgan` command.

Please check the README or [the docs](https://dai-lab.github.io/TGAN/readme.html#installation) for more details about how to install and run the new version.

Let us know if this resolves your doubt and feel free to close this issue if it does!

**Comment by soft-nougat** [comment]
Thanks Csala! Closing this one. :))
