### ISSUE TITLE
census data postprocessing issue

### ISSUE THREAD

**Issue by Venseven** [DAI-Lab/TGAN#23]
I have trained the census data ....after training and on restoring checkpoints it kind of stucks in generating samples...have attached the issue
![issue](https://user-images.githubusercontent.com/47088590/58185593-01b29280-7cd1-11e9-8141-1476d3401a4a.png)

**Comment by ManuelAlvarezC** [comment]
Hi @Venseven,

Would you mind sharing with us which version of TGAN you used and the commands you run?

Thanks

**Comment by Venseven** [comment]
`
import tgan
num_samples=100
model_path="models/covertype_1.pkl"
from tgan.data import load_demo_data
data,c_m=load_demo_data("census")
from tgan.model import TGANModel
tgan_m=TGANModel(c_m,gpu=0)
tgan_m.fit(data)
sample=tgan_m.sample(num_samples)
print(sample)`



tgan --version-0.1.0

**Comment by ManuelAlvarezC** [comment]
I think that the issue here is that you are trying to sample too few records ( less than the batch size, that defaults to 200). If you try with 1000 samples it should work perfectly.
