### ISSUE TITLE
Issue with the output of the model

### ISSUE THREAD

**Issue by culeforlife** [DAI-Lab/TGAN#26]
Hello everyone. I'm new to GANs as I need them to create more tabular data for my database. I came across this implementatin (thank you btw), but I have a problem with the output at the .sample() step. I've changed the parameter to test first, here's my code : 

tgan = TGANModel(continuous_columns,output='output',max_epoch=5,steps_per_epoch=1000,save_checkpoints=True,restore_session=True,batch_size=200,z_dim=200,noise=0.2,l2norm=0.00001,learning_rate=0.001,num_gen_rnn=100,num_gen_feature=100,num_dis_layers=1,num_dis_hidden=100,optimizer='AdamOptimizer')

Here's the output : 
![Capture](https://user-images.githubusercontent.com/36825741/60499790-0e071380-9cb1-11e9-9829-288a503fecfb.PNG)

It keeps running, looks like an infinite loop. I'm a beginner, I'm wondering where  I am mistaken, please enlighten me.

**Comment by ManuelAlvarezC** [comment]
Hi @culeforlife, and thanks for reporting this issue.

This is a known error and  can be solved by just changing the `num_samples` to a value higher than the `batch_size`.

**Comment by culeforlife** [comment]
Thank you for answering ! I wanted to try with your suggestion, but I'm getting another error : 
InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [100,5] rhs shape= [100,43]
	 [[{{node 2860522807872/Assign_786}}]]

I guess it's due to checkpoint, but I have no idea from where can I delete it, any idea please ?

**Comment by culeforlife** [comment]
Thank you for answering ! I wanted to try with your suggestion, but I'm getting another error :
InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [100,5] rhs shape= [100,10]
[[{{node 2617800806904/Assign_624}}]]

Any idea please ?

**Comment by culeforlife** [comment]
All good now, thanks !
