### ISSUE TITLE
Computation time 

### ISSUE THREAD

**Issue by culeforlife** [DAI-Lab/TGAN#27]
Hi, I have a question about the computation time needed ! In my case, I have a dataset of 1450 rows and 168 features and it takes about 2 hours and 16minutes to generate samples witch 5 epochs and 100 steps per epoch. This means that I will need days in order to run the model with 10000 steps. Is this normal ?
PS : I have 8GB of RAM

**Comment by ManuelAlvarezC** [comment]
Hi @culeforlife,

Yes, it's normal. The training of TGAN lasts for quite long, we even warn about it in the README:

> **NOTE** Depending on the performance of the system you are running, and the parameters selected for the model, this step can take up to a few hours.
