### ISSUE TITLE
Negative samples

### ISSUE THREAD

**Issue by Venseven** [DAI-Lab/TGAN#28]
My original data's columns contains some sparse negative columns and some zeros ....After generation  it becomes like a dense negative columns and there is no zeros ...instead of zeros they are like constant negative samples...How can i overcome this sampling?

**Comment by ManuelAlvarezC** [comment]
Hi @Venseven,

Could you please provide us some more information, such as:

- Python version/OS.
- Hyperparameters for `TGANModel`.
- An example of the input given and output generated.
- Any warning or error message that may appear during the fit or sampling.

Thanks.

**Comment by csala** [comment]
Closing this issue, as it has been inactive for two months. Please, feel free to open it again in case you can provide some more details about it!
