### ISSUE TITLE
How the attention is created.

### ISSUE THREAD

**Issue by MurugeshMarvel** [DAI-Lab/TGAN#29]
Forgive me if this is naive. You are applying softmax to the variable `attw` immediately after creating it without performing operations with respect to the input or any other variable. This is different from the conventional attention mechanisms that  I am used to in NLP. Is there any particular reason?

**Comment by leix28** [comment]
It's different. In NLP, the attention weights depend on the context. So the model should use the hidden representation of the context to generate an attention weight. However, here in synthetic tabular data, the correlation is somewhat fixed. So it is easier and more effective to simply learn the attention weight.

**Comment by ManuelAlvarezC** [comment]
Hi @MurugeshMarvel, 

Did Lei's answer solve your issue? If so, please feel free to close this issue. 

Thanks.

**Comment by MurugeshMarvel** [comment]
thanks @leix28
