### ISSUE TITLE
example doesn't run

### ISSUE THREAD

**Issue by georgeMcMahon** [DAI-Lab/TGAN#32]

**Comment by ManuelAlvarezC** [comment]
HI @georgeMcMahon,

Could you please provide us some more information, such as:

- Python version/OS.
- Hyperparameters for `TGANModel`.
- Any warning or error message that may appear during the fit or sampling.

Thanks.

**Comment by georgeMcMahon** [comment]
Hi manuel,

apologies - this was not TGANs error but my own I think. It is working fine now,

thanks,

George
