### ISSUE TITLE
Question: Running on GPU - VM instance

### ISSUE THREAD

**Issue by amarek1** [DAI-Lab/TGAN#34]
Hello,
I am trying to run my TGAN on a Google VM instance with 1 GPU. I am passing an argument 'gpu=0' or 'gpu='0'' to my TGANModel() but it keeps running on CPU rather than GPU. Could you please let me know what I might be doing wrong, is running on GPU supported while just passing a gpu argument or is there something else I should be doing to enable it? 
Thank you

```
from tgan.model import TGANModel
tgan = TGANModel(continuous_columns=continuous, output='tGAN/', gpu=0, max_epoch=1, steps_per_epoch=6000, save_checkpoints=True,
                 restore_session=True, batch_size=256, z_dim=200, noise=0.2, l2norm=0.00001, learning_rate=0.001,
                 num_gen_rnn=100, num_gen_feature=100, num_dis_layers=1, num_dis_hidden=100, optimizer='AdamOptimizer')
tgan.fit(data)
tgan.save(model_path, force=True)
```

**Comment by csala** [comment]
Hi @amarek1 this `gpu` argument was left from the first implementation, but it is not being used for anything a.t.m.

It was left there because it will be used again once we re-enable the Multi-GPU support (please check https://github.com/DAI-Lab/TGAN/issues/21)

In the meantime, in order to run the project on a single GPU, all you need to do is to manually remove `tensorflow` and install `tensorflow-gpu` after installing `tgan`:

```
pip install tgan
pip uninstall tensorflow
pip install "tensorflow>=1.13.0,<2.0"
```

**Comment by amarek1** [comment]
Thank you very much for your help, it works now.

**Comment by leoAshu** [comment]
I have tensorflow-gpu = 1.15.2
CUDA = 10.1 and corresponding cudnn
Upon running the tgan model, it still is using the CPU

Also, I have manually uninstalled tensorflow

Code:

from tgan.model import TGANModel
tgan = TGANModel(continuous_columns)
tgan.fit(data)

**Comment by afshinmarani** [comment]
> I have tensorflow-gpu = 1.15.2
> CUDA = 10.1 and corresponding cudnn
> Upon running the tgan model, it still is using the CPU
> 
> Also, I have manually uninstalled tensorflow
> 
> Code:
> 
> from tgan.model import TGANModel
> tgan = TGANModel(continuous_columns)
> tgan.fit(data)

Were you able to solve your problem?
