### ISSUE TITLE
documentation - checkpointing and reusing models

### ISSUE THREAD

**Issue by magneticnorth** [DAI-Lab/TGAN#4]
Hi. This is very interesting software. Thank you for providing it.  It seems to run stably.  Congratulations, this is not easy.

How do you restart a training run from a checkpoint? 

How do you generate new data from an existing model?

**Comment by leix28** [comment]
`launcher.py` is designed to automatically do hyper parameter random search  on multiple datasets. Thus it is not very straightforward to restart training and generate new data from an existing model. But you can still do that.

- Go to the experiment folder, find the `param.json`, and get all the hyper parameters.
- To restart training, run `python3 src/TGAN_synthesizer.py [...] --data xxx.npz --load xxx.ckpt`. You can find `xxx.npz` in the experiment folder generated by launcher. `xxx.ckpt` is the checkpoint you want to load. `[...]` are all the hyper parameters in `param.json`. 
- To generate new data, run `python3 src/TGAN_synthesizer.py [...] --data xxx.npz --load xxx.ckpt --sample 1000`. It can sample 1000 new rows from the saved model.
