### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [DAI-Lab/TGAN#7]
Why i faced this error? I thought that `synthetic1_4.npz` is automatically generated
`FileNotFoundError: [Errno 2] No such file or directory: 'expdir/KDD/synthetic1_4.npz'`

**Comment by ManuelAlvarezC** [comment]
Hi @TrinhDinhPhuc, 

Would you mind sharing with us some more details like:
- OS version
- Python version
- List of steps to reproduce the error + Full output
- Contents of the json config file

Thanks.

**Comment by TrinhDinhPhuc** [comment]
Hi I am using Ubuntu 18.04, python 3.6, this is my configuration file
 [
    {
        "name": "census",
        "num_random_search": 10,
        "train_csv": "data/census-train.csv",
        "continuous_cols": [0, 2, 3, 4, 5],
        "epoch": 5,
        "steps_per_epoch": 10000,
        "output_epoch": 3,
        "sample_rows": 10000
    }
]

**Comment by TrinhDinhPhuc** [comment]
I just simply run $python3.6 launcher.py demo_config as the instructions in README

**Comment by TrinhDinhPhuc** [comment]
Seems like i know why. I run `python3.6`, but the script was profiling `profiling:/home/harry/Downloads/Python-3.7.2/Parser/parser.gcda:Cannot open`. That why python3.7 said numpy  hasn't installed yet but actually numpy has installed on python3.6
`harry@Harry-Savage:~/Documents/GANs-demo/TGAN-master$ python3.6 src/launcher.py src/demo_config.json 
[{'name': 'KDD', 'num_random_search': 10, 'train_csv': 'data/KDD.csv', 'continuous_cols': [0, 2, 3, 4, 5], 'epoch': 5, 'steps_per_epoch': 10000, 'output_epoch': 3, 'sample_rows': 10000}]
working dir:  expdir/KDD
Traceback (most recent call last):
Traceback (most recent call last):
  File "src/TGAN_synthesizer.py", line 7, in <module>
  File "src/TGAN_synthesizer.py", line 7, in <module>
    import numpy as np
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'
profiling:/home/harry/Downloads/Python-3.7.2/Parser/parser.gcda:Cannot open
profiling:/home/harry/Downloads/Python-3.7.2/Parser/parser.gcda:Cannot open
profiling:/home/harry/Downloads/Python-3.7.2/Python/structmember.gcda:Cannot open
profiling:/home/harry/Downloads/Python-3.7.2/Python/structmember.gcda:Cannot open
profiling:/home/harry/Downloads/Python-3.7.2/Python/mystrtoul.gcda:Cannot open
`

**Comment by ManuelAlvarezC** [comment]
@TrinhDinhPhuc reading your messages, I suspect that you are installing TGAN and running it natively, without a virtualenv, and this is why your python interpreters are getting mixed.

To solve this, I would like to recommend you [to use a virtualenv](https://docs.python-guide.org/dev/virtualenvs/#virtualenvwrapper). Can you try it?

The commands should be something along these lines:

```
sudo apt-get install virtualenvwrapper
mkvirtualenv -p $(which python3.6) TGAN
cd path/to/TGAN 
python src/launcher.py demo_config.json
```

You deactivate the virtualenv with the command `deactivate` and activate it back with `workon TGAN`

**Comment by TrinhDinhPhuc** [comment]
You're awesome, thank you!
I have another question, I will open a new issue, not in this. Please close this thread.
