### ISSUE TITLE
Some questions about TGAN

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [DAI-Lab/TGAN#8]
While reading the paper, I have a few questions about TGAN:
* Can TGAN generate labels as well or just features?
* How much of synthetic data should I set to generate? (For example, I have tabular data with 100.000rows and 6 columns)
* Could you give me the description of this dataset? `https://s3.amazonaws.com/hdi-demos/tgan-demo/census-train.csv`

**Comment by leix28** [comment]
- Can TGAN generate labels as well or just features?
  - Yes. Both features and labels are considered columns in a table, so there's nothing different between labels and features. 

- How much of synthetic data should I set to generate? (For example, I have tabular data with 100.000rows and 6 columns)
  - You can generate as much as you like.

- Could you give me the description of this dataset? 
  - Here is the original dataset. https://archive.ics.uci.edu/ml/datasets/census+income.

**Comment by TrinhDinhPhuc** [comment]
Thank you. 
A few more questions:
I am using TGAN for KDD dataset, here are 6 futures that I have chosen and 1 label`(duration: numerical, protocol_type: categorical, Src_bytes: numerical, Dst_bytes: numerical, Count: numerical, Srv_Count: numerical, label: categorical)` 
And here is sample one row which I extracted from `synthetic0_1.npz` and read it using `numpy`:
```
>>> a.shape
(5000, 6)
>>> a[0]
array([-9.9999529e-01,  1.0000000e+00,  6.7457329e-20,  1.1078949e-17,
        1.4016924e-16,  9.3192446e-24], dtype=float32)
```
This is real data
`[5607, tcp, 0, 0, 223,23, normal]`
My question for this is why the synthetic data was being scaled so small? And why synthetic data missing 1 column? My `.csv` input file has 7 columns.

**Comment by TrinhDinhPhuc** [comment]
Also, there is one problem occurred. Which I have not trained TGAN successfully yet
https://github.com/tensorpack/tensorpack/issues/1123, please help me this.

**Comment by ManuelAlvarezC** [comment]
The questions about training your model are being answered [here](https://github.com/DAI-Lab/TGAN/issues/9), so I'll close this issue.

**Comment by TrinhDinhPhuc** [comment]
Please close this issue https://github.com/DAI-Lab/TGAN/issues/9 not this one. Because the question above has not been answered. Thank you.

**Comment by ManuelAlvarezC** [comment]
Hi @TrinhDinhPhuc,

> Please close this issue #9 not this one. Because the question above has not been answered. Thank you.

Sorry, I had not seen it. Let's get it answered.

> My question for this is why the synthetic data was being scaled so small?

This is because the `npz` contents are not yet the final output.

This file contains an intermediate output which still needs to be post-processed in order to produce
the actual sampling output, which will end up being stored in a `.csv` file.

The file which you should be looking for is called `synthesized0_1.csv`. If you cannot find it, the training
process might have not finished succesfully.

Did any errors show up in the logs while training?

> And why synthetic data missing 1 column? My .csv input file has 7 columns.

I can't be sure but it will help if you show us some raw lines of your CSV file, so we can figure it out together.

**Comment by TrinhDinhPhuc** [comment]
Yes, you're right. I could not find `synthesized0_1.csv` file. Seems like training process haven't finished successfully yet.
Sure this is some raw lines of my CSV file:
```

0 | tcp | 491 | 0 | 2 | 2 | normal
0 | udp | 146 | 0 | 13 | 1 | normal
0 | tcp | 0 | 0 | 123 | 6 | neptune
0 | tcp | 232 | 8153 | 5 | 5 | normal
0 | tcp | 199 | 420 | 30 | 32 | normal
0 | tcp | 0 | 0 | 121 | 19 | neptune
0 | tcp | 0 | 0 | 166 | 9 | neptune
0 | tcp | 0 | 0 | 117 | 16 | neptune
0 | tcp | 0 | 0 | 270 | 23 | neptune
0 | tcp | 0 | 0 | 133 | 8 | neptune
0 | tcp | 0 | 0 | 205 | 12 | neptune
0 | tcp | 0 | 0 | 199 | 3 | neptune
0 | tcp | 287 | 2251 | 3 | 7 | normal
0 | tcp | 334 | 0 | 2 | 2 | warezclient


```

**Comment by TrinhDinhPhuc** [comment]
Oh, finally I have trained successfully. Would you mind review a little bit about this synthetic data (table on the right)? The result quite bad actually. As you can see in the real data (table on the left), there are no negative values. And the value of column `A` & `C`, seems like all rows their value is the average number of the whole column.
Here are those metrics I used:
[
    {
        "name": "KDD2",
        "num_random_search": 2,
        "train_csv": "data/KDD2.csv",
        "continuous_cols": [0, 2, 3, 4, 5],
        "epoch": 5,
        "steps_per_epoch": 200,
        "output_epoch": 3,
        "sample_rows": 200
    }
]
![Screenshot from 2019-04-02 09-14-55](https://user-images.githubusercontent.com/14198992/55367398-d361d380-5527-11e9-9cc1-92224175bd3d.png)

Also, could you explain to me these values in `exp-result.csv` file?
```

0.062684896457984 | 0.030622851203326 | 0.327656512353082
0.051571120172703 | 0.327536579515471 | 0.456424402334693

```

**Comment by ManuelAlvarezC** [comment]
Hi @TrinhDinhPhuc,

I think that in order for the model to be able to generate valid values, you should increase `steps_per_epoch` to values similar to  the ones present in the  `demo_config.json`, that is, **10000 steps per epoch**, which in turn will increase the training time.

**Comment by TrinhDinhPhuc** [comment]
Thank you. What about my question "Also, could you explain to me these values in exp-result.csv file?" above?

**Comment by csala** [comment]
> Thank you. What about my question "Also, could you explain to me these values in `exp-result.csv` file?" above?

@TrinhDinhPhuc this does not seem to be related to the questions which you opened this issue for, 
and also this is clearly explained in the README, so I think this issue can be closed already.

If you have any other doubt about TGAN which is not already responded on the README or [the paper](https://arxiv.org/pdf/1811.11264.pdf), please feel free to open a new issue to ask about it!
